version: '3.6'

services:
    web:
        container_name: nextpso-web
        image: node:16-alpine
        volumes:
            - .:/app
        working_dir: /app
        ports:
            - $PORT:3000
        command: sh -c "npm run build && npm run start"
